/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.aruizeac;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Double res = DijkstraArithmeticInterpretator.execute("(1+((2+3)*(4*5)))");
        System.out.println(res);
    }
}
